### ISSUE TITLE
issue 0xc000007b 

### ISSUE THREAD

**Issue by Vladislav-S** [bjorn/tiled#1338]
![5](https://cloud.githubusercontent.com/assets/18230343/17744853/33efaf38-64b2-11e6-9108-a7d0729046cd.png)

**Comment by Vladislav-S** [comment]
downloaded new NVIDIA drivers and now its work

**Comment by bjorn** [comment]
Well, you should not need to download NVIDIA drivers to get Tiled to work, so this is still a valid issue. It is a problem with the way the Visual Studio 2013 Runtime is shipped in the Tiled installer (and it's hence specific to 64-bit Tiled, since the 32-bit version is built with MinGW instead).

I tried to solve this issue by using the available Merge Modules, but so far it has not resulted in a usable installer for me so I must be doing something wrong.

**Comment by davidwesst** [comment]
I just hit is this issue this evening. I'm running Windows 10 v1607 and I'm sure I had it working before. Not sure what could have changed, but would like to help if I can.

I've installed the 32-bit to keep working on my game, but the 64-bit version continues to give me grief.

What info can I provide to help?

**Comment by Vladislav-S** [comment]
oh, thank you, but i dont need any help any more. (all my problems were resolved)

**Comment by Vladislav-S** [comment]
I bought a MacBook

**Comment by bjorn** [comment]
@Vladislav-S I'm happy to hear your MacBook resolved all your problems, but I still have [19 open issues](https://github.com/bjorn/tiled/issues?q=is%3Aissue+is%3Aopen+label%3A%22OS+X%22) on OS X. :-P

@davidwesst I eventually noticed what was up with the shipped DLLs and [fixed it](https://github.com/bjorn/tiled/commit/7fcd78653b8d5ef5fecd616b01f831cba59b0fd3) for the snapshot builds. Could you try a snapshot 64-bit build resolves your issue? You can find them at https://update.mapeditor.org/snapshots-win/. I'll make sure to include this fix in the 0.18.1 release as well, but it would be nice to know for sure whether it resolves this issue.

**Comment by davidwesst** [comment]
@bjorn I installed Tiled-0.18.1483-win64 and still have the same error. I've uninstalled the old versions, and re-installed, with still no luck.

Any ideas on how I can triage the issue on my system?

**Comment by bjorn** [comment]
@davidwesst Hmm, that's unfortunate. Could you try http://www.dependencywalker.com/ for figuring out which DLLs the `tiled.exe` is loading and whether they have the correct architecture?

**Comment by davidwesst** [comment]
I managed to get some time to triage it with dependency walker, and found a few things. I did a fresh install of the x64 MSI for version 18.1483. There are errors when I go through `tiled.exe`. Here's the log:

```
Error: At least one required implicit or forwarded dependency was not found.
Error: At least one module has an unresolved import due to a missing export function in an implicitly dependent module.
Error: Modules with different CPU types were found.
Warning: At least one delay-load dependency module was not found.
Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.
```

In regards to any DLLs with the incorrect architecture, there are two that are used through many of the DLLs:

+ MSVCP120.DLL
+ MSVCR120.DLL

Thoughts?

**Comment by bjorn** [comment]
That is strange, because these two DLLs are exactly the ones that I fixed. Did you check the path to see whether they are the ones shipping with Tiled (they are in the Tiled installation directory)?

**Comment by davidwesst** [comment]
Looks like it. I've included a screenshot, just in case I'm missing something:

![tiled](https://cloud.githubusercontent.com/assets/867084/22179000/46e5e69a-e00c-11e6-97a0-a8b3a9fb2b57.png)

**Comment by bjorn** [comment]
Hmm, indeed for some reason the MSI installer is still putting the wrong file:
```
MSI (s) (D0:40) [11:46:28:957]: Executing op: FileCopy(SourceName=MSVCP120.DLL,SourceCabKey=MSVCP120,DestName=MSVCP120.DLL,Attributes=512,FileSize=455488,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,Version=12.0.40649.5,Language=1033,InstallMode=58982400,,,,,,,)
MSI (s) (D0:40) [11:46:28:957]: File: C:\Program Files\Tiled\MSVCP120.DLL;	To be installed;	Won't patch;	No existing file
MSI (s) (D0:40) [11:46:28:957]: Source for file 'MSVCP120' is compressed
InstallFiles: File: MSVCP120.DLL,  Directory: C:\Program Files\Tiled\,  Size: 455488
```
The correct file for 64-bit should be 645 KiB, whereas here it installs a file of 445 KiB.

**Comment by bjorn** [comment]
After much time was lost trying different things, I think I know why this was going wrong (see the [commit message](c717d5ae003e19d1d2adaec5169d0b7fcdfd1cef)...).

@davidwesst I closed the issue because I'm pretty sure this was it, but please do still verify.

**Comment by davidwesst** [comment]
Works like a charm! :)

**Comment by MehdiChinoune** [comment]
I get this message when building tiled with MSYS2/MINGW-w64+Qt6.

**Comment by bjorn** [comment]
> I get this message when building tiled with MSYS2/MINGW-w64+Qt6.

This turned out to be an issue with the MSI installer. Are you building an installer or running a compiled Tiled directly? If the latter, are you sure the right DLLs are used?

**Comment by MehdiChinoune** [comment]
> > I get this message when building tiled with MSYS2/MINGW-w64+Qt6.
> 
> This turned out to be an issue with the MSI installer. Are you building an installer or running a compiled Tiled directly? If the latter, are you sure the right DLLs are used?

The latter, what do you mean by right DLLs? All DLLs are installed in the same location.

**Comment by bjorn** [comment]
> The latter, what do you mean by right DLLs? All DLLs are installed in the same location.

I'm asking because the issue you're responding to was originally caused by the installer shipping the wrong DLLs (mixing up 32 and 64-bit runtime DLLs). Also, when compiling Tiled the runtime DLLs are not installed alongside because they are expected to be already on the system or available in the library path. Only when building the Windows installer or a distributable .zip archive are the runtime DLLs copied, but since I never tried to build either using MSYS2 this process would likely be broken anyway.

I see you've pushed an update to `mingw-w64-tiled` (https://github.com/msys2/MINGW-packages/commit/a3608b3b62037274eb446c2609683558bc238495) - thanks for maintaining that btw! Does that mean you've been able to resolve the problem? I'd be curious to know what caused it.

**Comment by MehdiChinoune** [comment]
> I see you've pushed an update to `mingw-w64-tiled` ([msys2/MINGW-packages@a3608b3](https://github.com/msys2/MINGW-packages/commit/a3608b3b62037274eb446c2609683558bc238495)) - thanks for maintaining that btw! Does that mean you've been able to resolve the problem? I'd be curious to know what caused it.

I have built it against Qt5, the issue appears when built against Qt6.

**Comment by bjorn** [comment]
> I have built it against Qt5, the issue appears when built against Qt6.

I guess this not only means changing from Qt 5 to Qt 6, but also from 32-bit to 64-bit, given that Qt 6 only supports 64-bit? Or is the Qt 5 package already using 64-bit? I wouldn't know what else could be causing this, unfortunately.

**Comment by MehdiChinoune** [comment]
> > I have built it against Qt5, the issue appears when built against Qt6.
> 
> I guess this not only means changing from Qt 5 to Qt 6, but also from 32-bit to 64-bit, given that Qt 6 only supports 64-bit? Or is the Qt 5 package already using 64-bit? I wouldn't know what else could be causing this, unfortunately.

We already using 64-bit.
