### ISSUE TITLE
XCB error: 3 (BadWindow) on startup

### ISSUE THREAD

**Issue by dnaf** [bjorn/tiled#1557]
I'm trying to run Tiled 0.18.2 on Arch Linux, using i3 as a window manager if that matters. I installed it from the package repository.

When I try to run it, the terminal gives the following output and stops. No windows are created and nothing else happens.

```
$ tiled
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::drawRects: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::translate: Painter not active
QPainter::drawPath: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::drawRects: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::drawRects: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::translate: Painter not active
QPainter::drawPath: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::drawRects: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::drawRects: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::translate: Painter not active
QPainter::drawPath: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::drawRects: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::drawRects: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::translate: Painter not active
QPainter::drawPath: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::drawRects: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::drawRects: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::translate: Painter not active
QPainter::drawPath: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::drawRects: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::drawRects: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::translate: Painter not active
QPainter::drawPath: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::drawRects: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::drawRects: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::translate: Painter not active
QPainter::drawPath: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::drawRects: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::drawRects: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::translate: Painter not active
QPainter::drawPath: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::drawRects: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::drawRects: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::translate: Painter not active
QPainter::drawPath: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::drawRects: Painter not active
QPainter::restore: Unbalanced save/restore
QWidget::setMinimumSize: (layerDock/Tiled::Internal::LayerDock) Negative sizes (4,-1) are not possible
QWidget::setMaximumSize: (layerDock/Tiled::Internal::LayerDock) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (TilesetDock/Tiled::Internal::TilesetDock) Negative sizes (99,-1) are not possible
QWidget::setMaximumSize: (TilesetDock/Tiled::Internal::TilesetDock) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (TerrainDock/Tiled::Internal::TerrainDock) Negative sizes (80,-1) are not possible
QWidget::setMaximumSize: (TerrainDock/Tiled::Internal::TerrainDock) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (miniMapDock/Tiled::Internal::MiniMapDock) Negative sizes (50,-1) are not possible
QWidget::setMaximumSize: (miniMapDock/Tiled::Internal::MiniMapDock) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (propertiesDock/Tiled::Internal::PropertiesDock) Negative sizes (2,-1) are not possible
QWidget::setMaximumSize: (propertiesDock/Tiled::Internal::PropertiesDock) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (ObjectsDock/Tiled::Internal::ObjectsDock) Negative sizes (2,-1) are not possible
QWidget::setMaximumSize: (ObjectsDock/Tiled::Internal::ObjectsDock) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (layerDock/Tiled::Internal::LayerDock) Negative sizes (32,-1) are not possible
QWidget::setMaximumSize: (layerDock/Tiled::Internal::LayerDock) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (TerrainDock/Tiled::Internal::TerrainDock) Negative sizes (80,-1) are not possible
QWidget::setMaximumSize: (TerrainDock/Tiled::Internal::TerrainDock) Negative sizes (524287,-1) are not possible
QXcbConnection: XCB error: 2 (BadValue), sequence: 440, resource id: 0, major code: 1 (CreateWindow), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 441, resource id: 85983237, major code: 2 (ChangeWindowAttributes), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 442, resource id: 85983237, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 443, resource id: 85983237, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 444, resource id: 85983237, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 446, resource id: 85983237, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 447, resource id: 85983237, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 448, resource id: 85983237, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 451, resource id: 85983237, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 455, resource id: 85983237, major code: 2 (ChangeWindowAttributes), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 456, resource id: 85983237, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 459, resource id: 85983237, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 460, resource id: 85983237, major code: 20 (GetProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 464, resource id: 85983237, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 465, resource id: 85983237, major code: 19 (DeleteProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 468, resource id: 85983237, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 469, resource id: 85983237, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 470, resource id: 85983237, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 471, resource id: 85983237, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 488, resource id: 85983237, major code: 2 (ChangeWindowAttributes), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 489, resource id: 85983237, major code: 2 (ChangeWindowAttributes), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 490, resource id: 85983237, major code: 20 (GetProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 491, resource id: 85983237, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 492, resource id: 85983237, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 493, resource id: 85983237, major code: 19 (DeleteProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 494, resource id: 85983237, major code: 20 (GetProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 495, resource id: 85983237, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 496, resource id: 85983237, major code: 20 (GetProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 497, resource id: 85983237, major code: 19 (DeleteProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 498, resource id: 85983237, major code: 8 (MapWindow), minor code: 0
QWidget::setMinimumSize: (layerDock/Tiled::Internal::LayerDock) Negative sizes (32,-1) are not possible
QWidget::setMaximumSize: (layerDock/Tiled::Internal::LayerDock) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (ObjectsDock/Tiled::Internal::ObjectsDock) Negative sizes (2,-1) are not possible
QWidget::setMaximumSize: (ObjectsDock/Tiled::Internal::ObjectsDock) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (TilesetDock/Tiled::Internal::TilesetDock) Negative sizes (99,-1) are not possible
QWidget::setMaximumSize: (TilesetDock/Tiled::Internal::TilesetDock) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (TerrainDock/Tiled::Internal::TerrainDock) Negative sizes (80,-1) are not possible
QWidget::setMaximumSize: (TerrainDock/Tiled::Internal::TerrainDock) Negative sizes (524287,-1) are not possible
QWidget::setMinimumSize: (propertiesDock/Tiled::Internal::PropertiesDock) Negative sizes (2,-1) are not possible
QWidget::setMaximumSize: (propertiesDock/Tiled::Internal::PropertiesDock) Negative sizes (524287,-1) are not possible
QXcbConnection: XCB error: 3 (BadWindow), sequence: 500, resource id: 85983237, major code: 18 (ChangeProperty), minor code: 0
```

Apologies if I'm doing something wrong!

**Comment by bjorn** [comment]
> I'm trying to run Tiled 0.18.2 on Arch Linux, using i3 as a window manager if that matters. I installed it from the package repository.

Hmm, this doesn't look like an issue specific to Tiled. Can you run other Qt 5 based applications just fine?

**Comment by dnaf** [comment]
@bjorn Yep. Just tried a few qt5 apps at random and they all seem to work. I'll try running it with a different WM later today.

**Comment by dnaf** [comment]
Same issue under openbox; window manager's not the issue

**Comment by bjorn** [comment]
I have no idea what could cause this, sorry.

Could you try running some other versions? Like the AppImage version for Linux that you can [download from itch.io](https://thorbjorn.itch.io/tiled) ("release" and/or "snapshot"). Or maybe trying a version compiled yourself.

**Comment by dnaf** [comment]
Oh, seems to work in the snapshot build and when built from source. Guess this issue's fixed now!

**Comment by bjorn** [comment]
@dnaf Did you try the "release" build from itch.io to see if that 0.18.2 version also has this problem? I think since we don't know what is causing it, it may as well be that the next Tiled release packaged for Arch Linux will still have this problem. I never heard of this problem before.

**Comment by dnaf** [comment]
The release build had the issue as well

**Comment by bjorn** [comment]
Alright, thanks good news since then it's indeed likely fixed. Thanks for testing!
